### ISSUE TITLE
Activates wrong window of multiple buffer windows

### ISSUE THREAD

**Issue by kopischke** [zhimsel/vim-stay#27] opened 2016-04-03 12:23 UTC
_stay_ will always jump back to the first (numerically lowest) window displaying a buffer when a window is closed, instead of the last window that was active. This causes issues like:
- https://github.com/junegunn/fzf/issues/532
- https://github.com/junegunn/fzf.vim/issues/105

The root cause is naive usage of `bufwinnr()` to get the window number to jump to.

**Comment by zhimsel** [comment] 2016-04-07 13:10
@kopischke Looks like the `fix/winjump` branch fixes the issue. Thanks!

**Comment by kopischke** [comment] 2016-04-07 13:20
Good to know, thanks for testing. The release is almost ready (this morning, I would have left out the “almost”, but something new turned up at the last second).

**Comment by zhimsel** [comment] 2016-04-07 13:24
No problem, thanks for fixing it :)

**Comment by kopischke** [comment] 2016-04-16 23:19
@zhimsel the fix in that branch actually didn’t do what I thought it did (the improvement you observed was incidental to me removing `BufLeave` from the event list, not anything else). I have since refactored the whole event and window selection logic and would be very glad if you could take a look at the [release/1.4.0](https://github.com/kopischke/vim-stay/tree/release/1.4.0) branch; in my testing, it fixes the issue.

**Comment by zhimsel** [comment] 2016-04-18 17:15
@kopischke Just switched to the `release/1.4.0` branch, and it introduces a new error when creating a new view (creating new windows, switching between them, etc): 

```
Error detected while processing function <SNR>54_MakeView:
line   16:
E712: Argument of extend() must be a List or Dictionary
```

**Comment by zhimsel** [comment] 2016-04-18 17:26
It's not present in `master` or `fix/winjump`

**Comment by kopischke** [comment] 2016-04-18 17:28
@zhimsel ugh, yeah, sorry about that, I fixed that error in another feature branch and forgot to include that fix. As a quick hack, you can just add the following line

``` vim
if empty(l:left) | let l:left = {} | endif
```

before [line 45 of plugin/stay.vim](https://github.com/kopischke/vim-stay/blob/release/1.4.0/plugin/stay.vim#L45). I’ll see that I push the complete fix later.

**Comment by kopischke** [comment] 2016-04-18 20:46
@zhimsel I just pushed an update to the release branch.

**Comment by zhimsel** [comment] 2016-04-19 19:54
@kopischke when working on c3d0d6a (as of now, `release/1.4.0/HEAD`), I now get the following error:

```
Error detected while processing function <SNR>54_MakeView[3]..stay#getbufstate:
line    3:
E706: Variable type mismatch for: l:state
```

This happens with or without adding the line you mentioned above before line 45 (or after, for that matter). For clarity, I would be applying this diff: 

``` diff
diff --git a/plugin/stay.vim b/plugin/stay.vim
index 1e31ea4..d3418d2 100644
--- a/plugin/stay.vim
+++ b/plugin/stay.vim
@@ -42,6 +42,7 @@ function! s:MakeView(stage, bufnr, winid) abort
   " do not create a view session if a call with a lower {stage} number
   " did so recently (currently hardwired to 1 second or less ago)
   let l:state = stay#getbufstate(a:bufnr)
+  if empty(l:left) | let l:left = {} | endif
   let l:left  = get(l:state, 'left', {})
   if a:stage > 1 && !empty(l:left) && localtime() - get(l:left, a:stage-1, 0) <= 1
     return 0
```

---

As an aside, I would highly discourage the use of force-pushing to a collaborative git repository. I would recommend reading this to learn why: https://developer.atlassian.com/blog/2015/04/force-with-lease/

**Comment by kopischke** [comment] 2016-04-19 20:25
Argh (again), yes, I forgot `getbufvar()` returns an empty String when the variable is undefined, so you get a type mismatch assigning a Dictionary; ~~vagaries of fast iteration on my side – stuff tends to remain in my Vim session longer than it should~~ _turns out [Vim patch 1547 removed sticky type checking](https://github.com/vim/vim/commit/f6f32c38bf3319144a84a01a154c8c91939e7acf), which is why I didn’t notice anything amiss; good riddance to that particular misfeature_. Thanks for testing and reporting back! 

Oh, and forget about the diff, BTW, that was a temporary workaround, no need for it after the last commits. The issue you encountered is fixed by inserting `unlet l:state` [before this line](https://github.com/kopischke/vim-stay/commit/c3d0d6adb830d7cd6809abc0ddc056517a11ee69#diff-c64ec9017efbb3ad83cd68c81fd97bc3R124) instead.

As to force pushing, I am well aware of the cons and keep a policy of never force pushing to `master`. For fix / feature branches like this one, however, it allows me to rebase interactively a lot to amend / fix up / squash without worrying about conflicts with the remote. Keep in mind that, practically speaking, such branches are private (nobody but me commits to them, ever – `--force-with-lease` is for all purposes identical to `--force` in that case) and they will unceremoniously be deleted once merged into `master` …

**Comment by kopischke** [comment] 2016-04-19 20:51
@zhimsel patch to apply:

``` patch
diff --git a/autoload/stay.vim b/autoload/stay.vim
index 251db74..3006605 100644
--- a/autoload/stay.vim
+++ b/autoload/stay.vim
@@ -120,8 +120,8 @@ endfunction
 " @returns:    Dictionary
 function! stay#getbufstate(bufnr) abort
   let l:state = getbufvar(a:bufnr, '_stay')
-  if empty(l:state)
-    let l:state = {}
+  if l:state is ''
+    unlet l:state | let l:state = {}
     call setbufvar(a:bufnr, '_stay', l:state)
   endif
   return l:state
```

**Comment by eapache** [comment] 2016-04-19 21:20
Could this also be the cause of https://github.com/vim-airline/vim-airline/issues/1131 ?

edit: I just tried `release/1.4.0` branch against that bug and there's no change; I'll file a separate issue if you want

**Comment by kopischke** [comment] 2016-04-19 21:45
@eapache yes, please do so. The current issue would manifest itself by landing you in the wrong window when closing another one; if I read your issue description correctly, that is not the case for https://github.com/vim-airline/vim-airline/issues/1131.

**Comment by kopischke** [comment] 2016-04-20 06:17
@eapache if I could bother you to create an issue soonish, that would be really helpful. Sorry to be pushy, but I’d love to get the next release out soon as the current issue is a rather serious bug, and I cannot reproduce your issue report on https://github.com/vim-airline/vim-airline/issues/1131 (I just up end having no window at all; I suppose some of your settings are different from mine, and would like to investigate that).

**Comment by eapache** [comment] 2016-04-20 12:27
No worries, created #29. Don't hold the release on my account though, it's been happening for a while so there's no regression.

**Comment by zhimsel** [comment] 2016-04-20 16:34
@kopischke that patch above (when applied to `release/1.4.0/HEAD`) resolves the issue, as far as I can tell.

**Comment by zhimsel** [comment] 2016-04-20 16:39
Although, I'm not sure if it's related, I'm getting this error sometimes when opening a file for the first time (it doesn't present if I quit and open the file again):

```
Error detected while processing function <SNR>54_LoadView[8]..stay#view#load:
line   35:
E119: Not enough arguments for function: s:exception2errmsg
E15: Invalid expression: "Vim error ".s:exception2errmsg()
```

**Comment by kopischke** [comment] 2016-04-20 16:44
That last error is unrelated, but thanks for reporting it!

**Comment by kopischke** [comment] 2016-04-21 06:15
@zhimsel I have pushed an update to the branch and I would be very grateful if you gave it a test ride.

**Comment by zhimsel** [comment] 2016-04-21 18:19
Works for me!

**Comment by zhimsel** [comment] 2016-04-21 18:19
Thanks for fixing this, by the way. It was driving me nuts before.

**Comment by kopischke** [comment] 2016-04-21 18:26
My pleasure. _vim-stay_ is meant to be the kind of plug-in you never notice – until you work with a Vim instance that lacks it, that is. Should you run into other issues in the future, do not hesitate to report them here!

**Comment by zhimsel** [comment] 2016-04-21 18:40
Will do, thanks! Would you mind shooting a notification message here when
1.4.0 is merged? I'd like to switch back to master once it is.

## 

Zach Himsel
zach@himsel.net
http://zach.himsel.net

On Thu, Apr 21, 2016 at 12:26 PM, Martin Kopischke <notifications@github.com

**Comment by kopischke** [comment] 2016-04-21 18:59
Of course, will do!

**Closed as completed** 2018-07-18 18:56 UTC
Labels: bug
