### ISSUE TITLE
Focus gets confused, ends up with no split focused

### ISSUE THREAD

**Issue by eapache** [zhimsel/vim-stay#29] opened 2016-04-20 12:25 UTC
Twin bug to https://github.com/vim-airline/vim-airline/issues/1131 as I'm still not sure which plugin is the actual culprit; they only seem to misbehave when together.

**Comment by eapache** [comment] 2016-04-20 12:30
This is reproducible for me with just vim-stay and vim-airline installed, no vimrc except the pathogen line, and a clean view folder, so I don't think there are any special settings involved? When I get to my proper computer I'll post the full build features of vim just in case.

**Comment by kopischke** [comment] 2016-04-20 12:50
@eapache thanks for posting the issue here. As [I said](https://github.com/kopischke/vim-stay/issues/27#issuecomment-212277447), my problem reproducing is that if I follow your steps literally, I end up having no open windows at all, so it seems I am missing something altogether. The output of `:version` would be quite useful, as [I have failed to notice issues due to fixes in one of the recent 800 or so patches before](https://github.com/kopischke/vim-stay/issues/27#issuecomment-212110811)…

**Comment by eapache** [comment] 2016-04-20 13:47
Full version:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  7 2016 13:51:17)
MacOS X (unix) version
Included patches: 1-1707
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl
+balloon_eval    +folding         +mouse_xterm     +terminfo
+browse          -footer          +multi_byte      +termresponse
++builtin_terms  +fork()          +multi_lang      +textobjects
+byte_offset     +fullscreen      -mzscheme        +timers
+channel         -gettext         +netbeans_intg   +title
+cindent         -hangul_input    +odbeditor       +toolbar
+clientserver    +iconv           +packages        +transparency
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      +mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        -mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Frameworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/Cellar/python/2.7.11/Frameworks -L/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.11/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby
```

I'm not sure how those steps could leave you with no window at all; you should have two splits open when you run the final `:bd` and there's no reason I can think of for `:bd` to close _multiple_ splits at once.

**Comment by kopischke** [comment] 2016-04-20 14:26
> there's no reason I can think of for `:bd` to close _multiple_ splits at once.

Isn’t that the expected behaviour when multiple windows (splits) show the same buffer?

**Comment by eapache** [comment] 2016-04-20 14:28
Not when there is another buffer in the background on the second split; the second split should (and does, for me) switch to showing the other buffer.

**Comment by kopischke** [comment] 2016-04-20 18:17
@eapache you are correct about the window behaviour, of course, I must not have followed your steps closely enough. Good news is I was able to reproduce the issue and I am pretty sure I have pinpointed the cause, but to confirm could you please tell me the output of `:echo &viewoptions`?

**Comment by eapache** [comment] 2016-04-20 18:34
`folds,options,cursor`

**Comment by kopischke** [comment] 2016-04-20 18:44
These are the Vim defaults – thank you, you just confirmed my diagnosis. To make a long story short, the issue is with `options`: with that flag in `&viewoptions`, view session files will store **all** local options, including `&statusline`, which confuses _airline_ after loading a view session file (I haven’t investigated in detail, but something like

``` vim
autocmd SessionLoadPost * AirlineRefresh
```

might mitigate the issue).

I have recommended a different setting in both the README and the help, but that obviously is not enough, so I will enforce `set-=options` while making views from the next release on (and restore the user’s `&viewoptions` afterwards, obviously – no plug-in should permanently alter user settings).

**Comment by eapache** [comment] 2016-04-20 18:48
So basically vim-stay was loading/restoring status-line values (since that's the default for mkview) which was confusing airline by changing its settings out from under it?

**Comment by kopischke** [comment] 2016-04-20 18:50
That’s the gist of it, yes.

**Comment by eapache** [comment] 2016-04-21 18:32
Thanks, the 1.4 release branch fixes this nicely.

**Comment by kopischke** [comment] 2016-04-21 19:01
Reopening until merged into master.

**Closed as completed** 2018-07-18 18:56 UTC
Labels: bug
