### ISSUE TITLE
Avoid doubling on Session Load 

### ISSUE THREAD

**Issue by Konfekt** [zhimsel/vim-stay#18] opened 2015-12-16 21:54 UTC
When loading a session, a SessionLoad variable is defined. Vim-Stay, if sessionoptions includes folds and cursorposition, should check for the existence of this variable and skip restore view, as restore session already takes care of everything.

**Comment by kopischke** [comment] 2015-12-17 01:01
Interesting catch. However, I’m wondering if sessions, views and _stay_’s handling of the latter actually ever collide. Unless I am missing something, the only way I can see them doing so is if buffers loaded via a session trigger `BufWinEnter`. Do they?

**Comment by Konfekt** [comment] 2015-12-17 12:43
Over here they do; the BufWinEnter is triggered.

**Comment by kopischke** [comment] 2015-12-17 13:33
OK. My current thinking goes like this: sessions have higher priority than views, meaning that losing view state after a session load is expected behaviour. The only way _stay_ may interfere with this I would call a bug is if it resets view state **after** the session has loaded. I don’t have access to my machine today, so could I impose on you and ask you to check if the `BufWinEnter` event fires before or after `SessionLoadPost`?

**Comment by Konfekt** [comment] 2015-12-17 14:39
No, everything is fine and in order. It's just that checking for g:SessionLoad speeds up session restore by skipping restore view.

**Comment by kopischke** [comment] 2015-12-17 14:44
True. OTOH, we can only safely skip view restoration if `&viewoptions` is a subset of `&sessionoptions`, and I’m not sure how big the performance impact of that kind of test would be, compared with the double load we currently have… 

**EDIT:** if this bothers you and you are certain the options duplicate restoration steps, you could set and unset `b:stay_ignore` in `SessionLoadPre` and `SessionLoadPost` respectively.

**Comment by Konfekt** [comment] 2015-12-17 20:39
For a couple of bigger tex files with expression or syntax folds, it takes a few seconds longer to restore them. Probably a check of the sessionoptions and viewoptions variables considerably less. It's just a suggestion. I am fine by disabling folds in sessionoptions.

**Comment by kopischke** [comment] 2015-12-17 21:43
A couple of seconds? Yikes. Will investigate the test scenario, then…

**Comment by kopischke** [comment] 2015-12-18 11:00
I’ve just had a good look at `&sessionoptions` and `&viewoptions` and I think I have hit a snag. As it turns out sessions seem to never store cursor position (`cursor` is not an option), which means that suppressing view loading to avoid double fold state processing would mean losing cursor position. That looks like a rather problematic trade off to me, but maybe you have some insight on that to share?

**Comment by Konfekt** [comment] 2015-12-18 15:13
I think that `cursor` is not opt-off, that is, a session reload will always restore the cursor position. That's what happens over here and `:h mksession` says

``` vim
...
7. Reloads the buffer list, with the last cursor positions.  If
   'sessionoptions' contains "buffers" then all buffers are restored,
   including hidden and unloaded buffers.  Otherwise only buffers in windows
   are restored.
...
```

**Comment by kopischke** [comment] 2015-12-18 15:31
… hmm, so that looks like _stay_ could just skip view loading if `&sessionoptions` contains “folds”.

**Comment by Konfekt** [comment] 2015-12-18 16:07
That's the idea and what FastFold does at

https://github.com/Konfekt/FastFold/blob/master/plugin/fastfold.vim#L70

**Comment by kopischke** [comment] 2015-12-19 10:11
@Konfekt added in https://github.com/kopischke/vim-stay/commit/4235f428a4440645c18dc642eb31522a18e65a05. Could you take the [fix/real-sessionload](https://github.com/kopischke/vim-stay/tree/fix/real-sessionload) branch for a test ride?

**Comment by Konfekt** [comment] 2015-12-19 13:26
Hmm.. Checked it but with the SessionLoad of CtrlSpace it still takes noticeably longer.

**Comment by kopischke** [comment] 2015-12-19 13:31
Hmm, could you report the output of

``` vim
:echo index(split(&sessionoptions, ','), '^folds$')
```

**Comment by Konfekt** [comment] 2015-12-19 17:02
`-1`

**Comment by kopischke** [comment] 2015-12-19 17:10
Argh, yes, I forgot something … how about

``` vim
:echo index(split(&sessionoptions, ','), 'folds'))
```

**Comment by Konfekt** [comment] 2015-12-19 17:25
`2`

**Comment by kopischke** [comment] 2015-12-19 21:50
Gotcha – will correct that.

**Comment by kopischke** [comment] 2015-12-19 22:31
Try the branch again, please.

**Comment by Konfekt** [comment] 2015-12-20 10:42
Everything seems good.

**Comment by kopischke** [comment] 2015-12-20 11:11
Good to know, thanks. Will be in the next release, then.

**Closed as completed** 2018-07-18 18:56 UTC
Labels: enhancement
