### ISSUE TITLE
"vim-stay could not read the view session file" for new files

### ISSUE THREAD

**Issue by eapache** [zhimsel/vim-stay#42] opened 2018-07-18 20:17 UTC
This is a regression today after upgrading to 1.4.0 of the plugin.

When opening an existing file that hasn't been opened before, or after clearing your view directory:
```
vim-stay could not read the view session file! Vim error E484: Can't open file /Users/eapache/.local/share/nvim/view/~=+test=
```

It doesn't seem to affect functionality, it's just annoying. It's gone subsequent openings of the file once the view file actually exists.

This is in Neovim from Homebrew on OSX:
```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
```

**Comment by eapache** [comment] 2018-07-18 20:22
An ad-hoc bisect seems to point the finger at one of 8b9b2f8, aa413be, or 09100db.

**Comment by zhimsel** [comment] 2018-07-18 20:41
Hm. What branch/commit were you on prior to this happening? `master` (and therefore v1.3.1)? or were you using the `release/1.4.0` branch?

**Comment by eapache** [comment] 2018-07-18 20:42
Master of the repo under the old owner (1.3.1). I only found out this was maintained again when I got the email for https://github.com/zhimsel/vim-stay/issues/29 closing.

**Comment by zhimsel** [comment] 2018-07-18 20:44
This is the same issue I was having on the `release/1.4.0` before I took over maintainership and merged it: https://github.com/zhimsel/vim-stay/issues/31

I'll close that issue as this one is more concise.

@kopischke you mentioned in #31 that you had a fix for that, but you never pushed it... would you be able to send me over a patch? or push it to a branch here?

I'll see if I can fix this in the meantime.

**Comment by zhimsel** [comment] 2018-07-18 21:04
@eapache you can use the [`hotfix/view-load-error`](https://github.com/zhimsel/vim-stay/compare/hotfix/view-load-error) branch for now to suppress the error message until I'm able to fix the root cause.

**Comment by blueyed** [comment] 2018-07-23 06:50
Bisected it to aa413be, but not really useful I think.

This happens only in Neovim because of this commit: https://github.com/neovim/neovim/commit/9b1c93937 - Vim silently does nothing: https://github.com/vim/vim/blob/947b39e761b8a95cc1bd37ad0c2c30552238809a/src/ex_docmd.c#L11916.

This appears to be a compatibility issue between Neovim/Vim, and I agree with @elmart somethow that this should not be silent, and therefore this patch should also get forwarded to Vim probably.

And in general it would be good to have a function that would return `get_view_file`, so that vim-stay could easily check if a view file exists, and not try to load it then (which always adds overhead / hooks).

/cc @elmart for the commit in Neovim

**Comment by blueyed** [comment] 2018-07-23 09:12
This appears to make sense for now:
```diff
diff --git i/autoload/stay/view.vim w/autoload/stay/view.vim
index ff230e9..556afef 100644
--- i/autoload/stay/view.vim
+++ w/autoload/stay/view.vim
@@ -95,7 +95,14 @@ function! stay#view#load(winid) abort
       silent! normal! zOzz
     endif
     return l:did_load_view
-  catch /\vE48[45]/ " no read access to existing view file
+  catch /E484/ " failed to open view file
+    " This happens with no view file on Neovim.
+    if !has('nvim')
+      let v:errmsg  = 'vim-stay could not open the view session file! '
+      let v:errmsg .= 'Vim error '.s:exception2errmsg(v:exception)
+    endif
+    return -1
+  catch /E485/ " no read access to existing view file
     let v:errmsg  = "vim-stay could not read the view session file! "
     let v:errmsg .= "Vim error ".s:exception2errmsg(v:exception)
     return -1
```

**Comment by StillStealSteel** [comment] 2018-07-24 16:59
@zhimsel plans on fix this?

**Comment by kopischke** [comment] 2018-07-24 17:35
@zhimsel Sorry for the delayed response, and doubly sorry for saying I must have hosed that fix at some point; it’s not in my local repo anymore. However, @blueyed’s patch is more or less exactly what I remember implementing, so that should be fine.

>And in general it would be good to have a function that would return get_view_file, so that vim-stay could easily check if a view file exists, and not try to load it then (which always adds overhead / hooks).

That would be exceedingly difficult with the current codebase, as _vim-stay_ has zero notion of view session files as such; the whole view session system is Vim’s and _stay_  just piggybacks on it. This almost total refusal to bypass or hack Vim internals is the reason why the plug-in kept working during years of neglect by yours truly, but it also makes some features structurally impossible to implement (the quoted one, or selective deletion of view files as requested in #41 for instance; note I said “almost” because there is a post hoc detection heuristic to ensure events fire properly, but even that is totally agnostic towards the mechanism used by Vim until the view session file is actually loaded).

This being said, I’m not the maintainer anymore and @zhimsel is of course free to ditch both my philosophy in developing _stay_ and the current codebase. That is what handover of maintainership means, after all 😉.

**Comment by blueyed** [comment] 2018-07-24 18:54
@kopischke 
I've meant that `get_view_file` should be exposed by Vim, so that vim-stay could use it.. :)
It currently supports the current buffer only, but could be changed to handle a buffer name instead maybe (for #41 etc).
Code: https://github.com/vim/vim/blob/947b39e761b8a95cc1bd37ad0c2c30552238809a/src/ex_docmd.c#L11925

Thanks for all your great work! :)

**Comment by zhimsel** [comment] 2018-07-24 19:12
@eapache @blueyed can you take a look at the [`hotfix/view-load-error`](https://github.com/zhimsel/vim-stay/compare/hotfix/view-load-error) branch again? I just pushed [@blueyed's patch](https://github.com/zhimsel/vim-stay/commit/0c688e238e94fa16cdd4d8e83c5da443e4ab6af6
) to it and tested locally. Seems to work fine. If everything works on your ends, I'll add that into `master`.

@blueyed thanks for that patch! I see what it's doing and it totally makes sense.

**Comment by eapache** [comment] 2018-07-26 12:12
Seems to work for me. Thanks!

**Comment by zhimsel** [comment] 2018-07-26 17:17
Ok, great! I'll apply that patch into master shortly.

**Comment by eapache** [comment] 2018-07-27 12:51
Hmm, now I'm getting `E227: mapping already exists for \d` instead. Not sure if it's strictly related to the fix for this or if it's just a different bug that's cropping up on master?

**Comment by zhimsel** [comment] 2018-07-27 16:48
@eapache under what conditions? Opening a file in vim that doesn't have a view file? What version of vim/neovim are you on?

And you're on vim-stay 1.4.1 right?

**Comment by eapache** [comment] 2018-07-27 17:07
Yes, same conditions and same neovim build as I originally filed at https://github.com/zhimsel/vim-stay/issues/42#issue-342476395. vim-stay 1.4.1 aka d69f611.

**Comment by zhimsel** [comment] 2018-07-27 17:08
Hm. Okay. Lemme do some testing and get back to you.

**Comment by kopischke** [comment] 2018-07-27 17:23
Err, I think I know what is going on: [the 1.4.1. patch](
https://github.com/zhimsel/vim-stay/commit/df3f12d57e0f7802d4c36dc7c93bd7a702c2da97) has clashed with the error handling logic. With Neovim, _stay_ 1.4.1’s `view#load` function returns -1 on `E484`, denoting an error, but does not set `v:errmsg`, which means the plug-in will happily signal a totally unrelated error (the one previously assigned to `v:errmsg`). The correct way IMO would be to invert the logic and set `v:errmsg` in all cases, but return 0 for Neovim, which would suppress the message by default while still allowing Neovim users to see the error if [they up the verbosity level.](
https://github.com/zhimsel/vim-stay/blob/d69f611329694766a1db45a8a99913bc687e6bb2/doc/vim-stay.txt#L67)

**Comment by zhimsel** [comment] 2018-07-27 17:27
@eapache I'm not getting that error in my environment under those conditions. I even tested neovim 0.3.0 (I was on 0.3.1 previously).

@kopischke I see what you're saying. I'll write up a patch and put it in a branch for @eapache to test.

**Comment by zhimsel** [comment] 2018-07-27 17:35
@eapache can you test out the [`hotfix/viewload_nvim_error_2` branch](https://github.com/zhimsel/vim-stay/compare/hotfix/viewload_nvim_error_2) and let me know how that works in your env?

**Comment by eapache** [comment] 2018-07-27 17:40
Works properly, thanks!

**Closed as completed** 2018-07-27 20:39 UTC
Labels: bug
